import logging
import subprocess

from docker.models.containers import Container


def stream_logs(container: Container) -> None:
    """Streams the logs generated by `containers.run` via the Docker SDK for Python."""
    for line in container.logs(stream=True, follow=True):
        logging.info(line.decode("utf-8", errors="ignore").strip())


def gpu_available() -> bool:
    """Returns whether the current environment has a GPU available."""
    return (
        subprocess.run(["nvidia-smi"], capture_output=True, text=True).returncode == 0
    )


def supports_flash_attention() -> bool:
    """Returns whether the current GPU supports Flash Attention or not (based on compute capability)."""
    output = subprocess.run(
        ["nvidia-smi", "--query-gpu=compute_cap", "--format=csv,noheader,nounits"],
        capture_output=True,
        text=True,
        check=True,
    )
    return float(output.stdout.strip()) >= 8.0
