import logging

from docker.models.containers import Container


def stream_logs(container: Container) -> None:
    """Streams the logs generated by `containers.run` via the Docker SDK for Python."""
    for line in container.logs(stream=True, follow=True):
        logging.info(line.decode("utf-8", errors="ignore").strip())
