apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi-server
  template:
    metadata:
      labels:
        app: tgi-server
        hf.co/model: google--gemma-7b-it
        hf.co/task: text-generation
    spec:
      containers:
        - name: tgi-container
          image: us-central1-docker.pkg.dev/gcp-partnership-412108/deep-learning-images/huggingface-text-generation-inference-tpu.0.1.4:latest
          resources:
            requests:
              google.com/tpu: 4
            limits:
              google.com/tpu: 4
          env:
            - name: MODEL_ID
              value: google/gemma-7b-it
            - name: PORT
              value: "8080"
            - name: MAX_INPUT_TOKENS
              value: "1000"
            - name: MAX_TOTAL_TOKENS
              value: "1024"
            - name: MAX_BATCH_SIZE
              value: "2"
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_token
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
        cloud.google.com/gke-tpu-topology: 2x2
