apiVersion: apps/v1
kind: Deployment
metadata:
  name: tei-deployment
  namespace: hf-gke-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tei-server
  template:
    metadata:
      labels:
        app: tei-server
        hf.co/model: BAAI--bge-base-en-v1
        hf.co/task: text-embeddings
    spec:
      serviceAccountName: hf-gke-service-account
      initContainers:
        - name: init
          image: google/cloud-sdk:slim
          command: ["sh", "-c"]
          args:
            - gcloud storage cp -r gs://$BUCKET_PATH /data
          env:
            - name: BUCKET_PATH
              value: hf-models-gke-bucket/bge-base-en-v1.5
          volumeMounts:
            - name: gcs-mount
              mountPath: /data
          resources:
            requests:
              cpu: 8.0
      containers:
        - name: tei-container
          image: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-text-embeddings-inference-cu122.1-4.ubuntu2204:latest
          resources:
            requests:
              nvidia.com/gpu: 1
          env:
            - name: MODEL_ID
              value: /data/bge-base-en-v1.5
            - name: NUM_SHARD
              value: "1"
            - name: PORT
              value: "8080"
            - name: HUGGINGFACE_OFFLINE
              value: "1"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /data
              name: gcs-mount
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: gcs-mount
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                storageClassName: ssd
                resources:
                  requests:
                    storage: 48Gi
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
