apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
  namespace: hf-gke-namespace
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-deployment
  namespace: hf-gke-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi-server
  template:
    metadata:
      labels:
        app: tgi-server
        hf.co/model: Qwen--Qwen2-7B-Instruct
        hf.co/task: text-generation
      annotations:
        deployment.kubernetes.io/max-replicas: "1"
    spec:
      serviceAccountName: hf-gke-service-account
      initContainers:
        - name: init
          image: google/cloud-sdk:slim
          command: ["sh", "-c"]
          args:
            - gcloud storage cp -r gs://$BUCKET_PATH /data
          env:
            - name: BUCKET_PATH
              value: hf-models-gke-bucket/Qwen2-7B-Instruct
          volumeMounts:
            - name: gcs-mount
              mountPath: /data
          resources:
            requests:
              cpu: 8.0
      containers:
        - name: tgi-container
          image: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-text-generation-inference-cu121.2-1.ubuntu2204:latest
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          env:
            - name: MODEL_ID
              value: /data/Qwen2-7B-Instruct
            - name: NUM_SHARD
              value: "1"
            - name: PORT
              value: "8080"
            - name: HUGGINGFACE_OFFLINE
              value: "1"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /data
              name: gcs-mount
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: gcs-mount
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: ssd
                resources:
                  requests:
                    storage: 48Gi
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
