
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-deployment
  namespace: hf-gke-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi-server
  template:
    metadata:
      labels:
        app: tgi-server
        hf.co/model: Qwen2-7B-Instruct
        hf.co/task: text-generation
      annotations:
        deployment.kubernetes.io/max-replicas: "1"
    spec:
      serviceAccountName: hf-gke-service-account
      initContainers:
        - name: init
          image: google/cloud-sdk:slim
          command: ["sh", "-c"]
          args:
            - gcloud storage cp -r gs://$BUCKET_PATH /data
          env:
            - name: BUCKET_PATH
              value: hf-models-gke-bucket/Qwen2-7B-Instruct
          volumeMounts:
            - name: gcs-mount
              mountPath: /data
          resources:
            requests:
              cpu: "4"
      containers:
        - name: tgi-container
          image: us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-text-generation-inference-cu121.2-0.ubuntu2204:latest
          # image: ghcr.io/huggingface/text-generation-inference:2.0.3 <- Qwen2 Template Error is fixed in 2.0.1 onwards, see https://github.com/huggingface/text-generation-inference/issues/1743#issuecomment-2066818605
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          env:
            - name: MODEL_ID
              value: /data/Qwen2-7B-Instruct
            - name: NUM_SHARD
              value: "1"
            - name: PORT
              value: "8080"
            - name: HUGGINGFACE_OFFLINE
              value: "1"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /data
              name: gcs-mount
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: gcs-mount
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteMany" ]
                storageClassName: ssd
                resources:
                  requests:
                    storage: 24Gi
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
