apiVersion: v1
kind: Service
metadata:
  name: tgi-service
  namespace: hf-gke-namespace
spec:
  selector:
    app: tgi-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
