name: Build images and run tests

on:
  workflow_call:
    inputs:
      dockerfile_path:
        description: 'Path to the Dockerfile'
        type: string
        required: true
      docker_image_tag: # It should be in the form as mentioned in our internal docs. Just pass insensitive data here like huggingface-text-generation-inference-${accelerator}.${version}:latest
        description: 'Docker Image Tag'
        type: string
        required: true

jobs:
  build-push-image:
    uses: ./.github/workflows/build_push_image.yml
    secrets: inherit
    with:
      region: us-central1
      dockerfile_path: ${{ inputs.dockerfile_path }}
      docker_image_tag: ${{ inputs.docker_image_tag }}
      gcp_artifact_registry_repository: deep-learning-images
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}

  model_test:
    needs: build-push-image
    uses: ./.github/workflows/test_model.yml
    secrets: inherit
    with:
      region: us-central1
      docker_image_tag: ${{ inputs.docker_image_tag }}
      gcp_artifact_registry_repository: deep-learning-images
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
