name: Build images and run tests

on:
  push:
    branches:
      - build_images_and_run_tests_*

jobs:
  build-push-image:
    strategy:
      fail-fast: false
      matrix:
        torch: [2.1]
        transformers: [4.38.1]
        python: [310]
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    with:
      dockerfile_path: ./containers/pytorch/training/gpu/${{ matrix.torch }}/transformers/${{ matrix.transformers }}/py${{ matrix.python }}/Dockerfile
      docker_image_tag: huggingface-pytorch-training-gpu-${{ matrix.torch }}.transformers.${{ matrix.transformers }}.py${{ matrix.python }}:latest
