name: Test Build and Push Image Reusable Workflow
on:
  push:
    branches:
      - feature/build-push-image-workflow
  workflow_dispatch:

jobs:
  test-reusable-workflow:
    uses: ./.github/workflows/build-push-image.yml
    with:
        region: us-central1
        dockerfile_path: ./containers/pytorch/2.1/transformers/4.37.2/py310/Dockerfile
        docker_image_tag: huggingface-pytorch-transformers-4.37.2-py310:latest
        gcp_artifact_registry_repository: deep-learning-images
    secrets:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT_JSON_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON_KEY }}