name: Model Test

on:
  push:
    branches:
      - draft_ci

env:
  HF_HOME: /mnt/cache
  # For gated repositories, we still need to agree to share information on the Hub repo. page in order to get access.
  # This token is created under the bot `hf-transformers-bot`.
  HF_HUB_READ_TOKEN: ${{ secrets.HF_HUB_READ_TOKEN }}

jobs:
  github_repo:
    name: github repo
    runs-on: [single-gpu, nvidia-gpu, a10, ci]
    container:
      # TODO: make this $ {{ inputs.image }} to use GCP's DLC images
      image: huggingface/transformers-all-latest-gpu
      options: --gpus all --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: run tests
        run: |
          python3 -m pytest -v tests/models
